- 파이토치의 선형 회귀 모델 ``nn.Linear()``라는 함수가 있다.
  - H(x) 개선
- 평균 제곱 오차 ``nn.functional.mse_loss()`` 라는 함수로 구현되어 있다

직접 구현하던 것들이 없어졌다

# nn.Module을 이용하여 단순 선형 회귀 구현

In [27]:
import torch
import torch.nn
import torch.nn.functional as F

In [28]:
torch.manual_seed(1)

In [29]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

하나의 입력 x에 대하여 하나의 출력 y를 가지므로 둘 다 1이다.

In [30]:
# 모델을 선언 및 초기화. 단순 선형 회귀이므로 input_dim=1, output_dim=1.
model = nn.Linear(1,1)

In [31]:
# model에는 가중치 W와 편향 b가 저장되어져 있다
# 랜덤 초기화가 되어져 있다
list(model.parameters())

[Parameter containing:
 tensor([[0.5153]], requires_grad=True),
 Parameter containing:
 tensor([-0.4414], requires_grad=True)]

In [32]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [33]:
n_epoch = 2000
for epoch in range(n_epoch+1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 개선
    # gradient를 0으로 초기화 -> 미분한 결과 W,b를 제대로 반영 할 수 있게 된다!!!
    optimizer.zero_grad()
    
    # 비용 함수를 미분하여 gradient 게싼
    cost.backward()
    
    # W와 b 업데이트
    optimizer.step()

    if not (epoch%200):
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, n_epoch, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  200/2000 Cost: 0.001724
Epoch  400/2000 Cost: 0.000658
Epoch  600/2000 Cost: 0.000251
Epoch  800/2000 Cost: 0.000096
Epoch 1000/2000 Cost: 0.000037
Epoch 1200/2000 Cost: 0.000014
Epoch 1400/2000 Cost: 0.000005
Epoch 1600/2000 Cost: 0.000002
Epoch 1800/2000 Cost: 0.000001
Epoch 2000/2000 Cost: 0.000000


In [34]:
# 예측
new_var = torch.FloatTensor([[4.0]])

pred_y = model(new_var) #forward 연산

print("훈련 후 예측값", pred_y)

훈련 후 예측값 tensor([[7.9989]], grad_fn=<AddmmBackward0>)


In [35]:
list(model.parameters())

[Parameter containing:
 tensor([[1.9994]], requires_grad=True),
 Parameter containing:
 tensor([0.0014], requires_grad=True)]

# nn.Module을 이용하여 다중 선형 회귀 구현하기

In [36]:
import torch
import torch.nn
import torch.nn.functional as F

In [37]:
torch.manual_seed(1)

In [39]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [40]:
model = nn.Linear(3,1)

In [41]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [42]:
n_epoch = 2000
for epoch in range(n_epoch+1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 개선
    # gradient를 0으로 초기화 -> 미분한 결과 W,b를 제대로 반영 할 수 있게 된다!!!
    optimizer.zero_grad()
    
    # 비용 함수를 미분하여 gradient 게싼
    cost.backward()
    
    # W와 b 업데이트
    optimizer.step()

    if not (epoch%200):
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, n_epoch, cost.item()
      ))

Epoch    0/2000 Cost: 31667.599609
Epoch  200/2000 Cost: 0.223911
Epoch  400/2000 Cost: 0.220059
Epoch  600/2000 Cost: 0.216575
Epoch  800/2000 Cost: 0.213413
Epoch 1000/2000 Cost: 0.210559
Epoch 1200/2000 Cost: 0.207967
Epoch 1400/2000 Cost: 0.205618
Epoch 1600/2000 Cost: 0.203481
Epoch 1800/2000 Cost: 0.201539
Epoch 2000/2000 Cost: 0.199770


In [43]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.2306]], grad_fn=<AddmmBackward0>)
