# 토치 텐서 연산

### View method

In [1]:
import torch

In [2]:
temp = torch.tensor([[1,2],[3,4]])

In [3]:
temp.shape

torch.Size([2, 2])

In [4]:
temp.view(4,1) # 4*1로 변경

tensor([[1],
        [2],
        [3],
        [4]])

In [5]:
temp.view(-1) # 1차원 벡터로 변경

tensor([1, 2, 3, 4])

In [6]:
temp.view(1,-1) # -1은 (1,?)와 같은 의미로 다른 차원으로부터 해당 값을 유추 하겠다.
# 여기서 유추란 temp의 원소 개수 (2*2)를 유지 한채 (1,?) 형태로 만들겠다.

tensor([[1, 2, 3, 4]])

In [7]:
temp.view(-1,1)

tensor([[1],
        [2],
        [3],
        [4]])

### torch max

In [29]:
import torch

In [41]:
y_pred = [[0.2,0.7,0.8,0.4],
          [0.4,0.2,0.6,0.1],
          [0.2,0.5,0.3,0.9]]
# y_pred = [[0.2,0.5,0.3,0.9]]

In [42]:
y_pred = torch.tensor(y_pred)

In [50]:
torch.max(y_pred,1) #1의 의미는 잘 모르겠음

torch.return_types.max(
values=tensor([0.8000, 0.6000, 0.9000]),
indices=tensor([2, 2, 3]))

In [51]:
torch.max(y_pred,0) #1의 의미는 잘 모르겠음

torch.return_types.max(
values=tensor([0.4000, 0.7000, 0.8000, 0.9000]),
indices=tensor([1, 0, 0, 2]))

### torch clone & detach

- clone
  - clone은 기존 텐서의 내용을 복사한 텐서를 생성하겠다는 의미이며,
- detach
  - detach는 기존 텐서에서 기울기가 전파되지 않는 텐서입니다.
즉 tensor.clone().detach()는 기존 텐서를 복사한 새로운 텐서를 생성하지만 기울기에 영향을 주지는 않겠다.

### torch clip

데이터를 주어진 값 사이로 제한하겠다는 의미

In [54]:
import numpy as np
exam = np.array([-1.8,-1.2, 0.0, 0.8])
print(exam)
print(np.clip(exam,-0.5, 0.5))

[-1.8 -1.2  0.   0.8]
[-0.5 -0.5  0.   0.5]


# 데이터

### 사용자 정의 커스텀 데이터 셋

In [ ]:
import torch.utils.data import Dataset
import torch.utils.data import DataLoader
class CustomDataset(Dataset):
    def __init__(self):
        pass
    def __len__(self): #전체 데이터셋의 크기를 반환합니다.
        pass
    def __item__(self): #전체 x와 y데이터 중 해당 idx번째의 데이터를 가져옵니다.
        pass

### DataLoader
- 데이터로더 객체는 학습에 사용될 데이터 전체를 보관했다가 모델 학습을 할 때 배치 크기만큼 데이터를 꺼내서 사용합니다. 이때 주의할 것은 미리 잘라 놓는 것이 아니라 내부적으로 반복자(iterator)에 포함된 인덱스(index)를 이용하여 배치 크기만큼 데이터를 반환한다는 것이다.

In [ ]:
dataset = DataLoader(tensor_dataset, batch_size = 4, shuffle = True)

In [ ]:
# 데이터 로더는 for문을 이용하여 구문을 반복 실행하는 것과 같다.
for i, data in enumerate(dataset):
    batch=data[0]

# 모델 정의
모델을 정의 하기 위해 모듈을 상속한 클래스를 사용한다.
- 계층: 모듈 또는 모듈을 구성하는 한 개의 계층
- 모듈: 한 개 이상의 계층이 모여서 구성된 것, 모듈이 모여 새로운 모듈 만들 수 있다.
- 모델: 최종적으로 원하는 네트워크, 한 개의 모듈이 모델이 될 수 있다.

## 단순 신경망을 정의하는 방법

In [ ]:
model = nn.Linear(in_features = 1, out_features = 1, bias = True)

## nn.Module()을 상속하여 정의 하는 방법
nn.Module을 상속받는 모델은 기본적으로 \_\_init__()과 forward() 함수를 포함한다.

- \_\_init__()은 모델에서 사용될 모듈, 활성화 함수 등을 정의
- forward()는 모델에서 실행되어야 하는 연산을 정의한다.

In [ ]:
class MLP(nn.Module):
    def __init__(self):
        pass
    def forward(self):
        pass

## Sequential 신경망을 정의하는 방법

In [ ]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer = nn.Sequential(
            nn.Conv2d(in_channels = 3, out_channels = 64, kernel_size = 5),
            nn.ReLU(inplace = True),
            nn.MaxPool2d(2)
        )
    def forward(self):
        pass

## 함수로 신경망을 정의하는 방법

In [ ]:
def MLP(in_features = 1, hidden_features = 20, out_features = 1):
    hidden = nn.Conv2d(in_channels = 3, out_channels = 64, kernel_size = 5),
    activation = nn.ReLU(inplace = True),
    pool = nn.MaxPool2d(2)
    net = nn.Sequential(hidden,activation, pool)
    return net

# 모델의 파라미터 정의

- 손실 함수: 출력과 실제 값 사이의 오차 측정 -> 모델의 정확성을 측정
  - BCELoss: 이진 분류
  - CrossEntropyLoss: 다중 클래스 분류
  - MSELoss: 회귀 모델
- 옵티마이저: 데이터와 손실함수를 바탕으로 모델의 업데이트 방법을 결정
  - optimizer는 step() 메서드를 통해 전달받은 파라미터를 업데이트 한다.
  - 모델의 파라미터별로 (learning rate) 다르게 적용 가능
  - zero_grad()는 옵티마이저에 사용된 파라미터들의 기울기를 0으로 만든다.
- 학습률 스케쥴러: 미리 지정한 횟수의 에폭을 지날 때마다 학습률을 감소 시켜 준다. 초기에는 빠른 학습을 하다가 전역 최소점 근처에 다다르면 학습률을 줄여서 최적점을 찾아갈 수 있게 도와준다.

# 모델 훈련
- 모델, 손실함수, 옵티마이저 정의
- 기울기 초기화 (optimizer.zero_grad())
- model output (출력) (output = model(input))
- 손실 함수로 오차 계산 (loss = loss_fn(output, target))
- 역전파 학습 (loss.backward())
- 기울기 업데이트 (optimizer.step())

# 모델 평가
# 훈련 과정 모니터링
- 텐서보드 사용

### model.eval()
torch.no_grad를 사용하여 기울기 값을 저장하지 않도록 한다. 토치는 모든 연산과 기울기 값을 저장하기 때문이다. -> 필요한 메모리와 연산 시간을 줄일 수 있다.

In [ ]:
model.eval()
with torch.no_grad():
    valid_loss = 0
    for x, y in valid_dataloader:
        outputs = model(x)
        loss = F.cross_entropy(outputs, y.long().squeeze())
        valid_loss += float(loss)
        y_hat += [outputs]
    valid_loss = valid_loss / len(valid_loader)

# Numpy stack, concatenate 차이

In [8]:
import numpy as np

In [9]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.array([[5,6],[7,8],[9,10]])

In [12]:
np.concatenate((a,b), axis = 0) #0이면 밑으로 쭉

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
np.concatenate((a,b), axis = 1) #1이면 옆으로 쭉

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [19]:
np.stack((a,b), axis = 0) #(2,2,2)
# stack은 여러 같은 차원을 합쳐 다음 차원을 만든다

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
np.concatenate((a,c), axis = 0) #0이면 밑으로 쭉

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [17]:
np.stack((a,c), axis = 0) #(2,2,2)

ValueError: all input arrays must have the same shape

# Numpy randint, rand

In [1]:
import numpy as np

In [2]:
np.random.randint(10) # 0~10임의의 숫자 출력

6

In [4]:
np.random.rand(8) # 0~1사이의 표준 정규 분포 난수를 행렬로 (1* 8) 출력

array([0.06512202, 0.24871075, 0.27347486, 0.81668293, 0.58424542,
       0.99329761, 0.98966703, 0.23611681])

In [5]:
np.random.rand(4,2) # 그 난수를 (4*2) 출력

array([[0.7134414 , 0.13935659],
       [0.61501823, 0.9503671 ],
       [0.63884066, 0.72220164],
       [0.12278518, 0.06363522]])

In [7]:
a = np.arange(0,100,3) # 1~99의 숫자에서 3씩 건너뛴 행렬을 생성

In [12]:
a.resize(6,5)

In [13]:
a

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42],
       [45, 48, 51, 54, 57],
       [60, 63, 66, 69, 72],
       [75, 78, 81, 84, 87]])

# 활성화 함수 지정 방법
- F.relu(): forward() 함수에서 정의
- nn.ReLU(): \_\_init__() 함수에서 정의

둘의 차이는 간단히 사용하는 위치이다. 근본적으로는 사용 방법에 차이가 있다.

In [23]:
import torch
import torch.nn as nn
inputs = torch.randn(64,3,244,244)
conv = nn.Conv2d(in_channels=3, out_channels= 64, kernel_size=3, padding=1)
outputs = conv(inputs)
layer = nn.Conv2d(1,1,3)

In [24]:
inputs.shape

torch.Size([3, 244, 244])

# Numpy transpose

In [25]:
import numpy as np

In [27]:
exam = np.arange(24).reshape(2,3,4)
exam 

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
np.transpose(exam, (2,1,0)) # 2번 인덱스 1번 인덱스../. 각각의 인덱스 값 -> (2,3,4) -> (4,3,2)로 변환

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])